### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by ImaginaryResources** [ImaginaryResources/x86-Calculator#1]
Things to implement

- [x] Finish all math operations
- [x] Make math operations procedures
- [ ] Move procedures to another file
- [x] Use printStr within printMenu
- [ ] Create UML ASCII comments for visuals
